### ISSUE TITLE
Tuneup of dart-services fails on macOS

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1022]
```bash
~/D/G/dart-services (master)> tuneup check
Checking project dart_services...       
Instance of 'ServerError'
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#19     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#20     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#21     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#22     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#23     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#24     _relink (package:analyzer/src/summary/link.dart:305:57)
#25     link (package:analyzer/src/summary/link.dart:123:3)
#26     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#29     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#30     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#31     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#32     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#33     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#34     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#35     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#36     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#37     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#38     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#39     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#40     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#46     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#47     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#48     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#49     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#50     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#51     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by domesticmouse** [comment]
I believe this has been fixed. Please re-check.

```bash
$ tuneup check
Checking project dart_services...       
No issues found; analyzed 43 source files in 3.6s.
```
