### ISSUE TITLE
Chrome 75 (beta) MutationObserver error in codelab

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1064]

**Comment by domesticmouse** [comment]
From Chrome's console:

```
Uncaught Instance of 'minified:ag'
    at Object.d (https://dartpad.dartlang.org/experimental/new_embed.dart.js:434:3)
    at mm.$0 (https://dartpad.dartlang.org/experimental/new_embed.dart.js:5764:20)
    at Object.rz (https://dartpad.dartlang.org/experimental/new_embed.dart.js:1418:5)
    at jO.rE (https://dartpad.dartlang.org/experimental/new_embed.dart.js:1420:7)
    at kv.$1 (https://dartpad.dartlang.org/experimental/new_embed.dart.js:4696:3)
    at ta (https://dartpad.dartlang.org/experimental/new_embed.dart.js:513:17)
    at MutationObserver.<anonymous> (https://dartpad.dartlang.org/experimental/new_embed.dart.js:522:51)

d @ new_embed.dart.js:434
$0 @ new_embed.dart.js:5764
rz @ new_embed.dart.js:1418
rE @ new_embed.dart.js:1420
$1 @ new_embed.dart.js:4696
ta @ new_embed.dart.js:513
(anonymous) @ new_embed.dart.js:522
childList (async)
$1 @ new_embed.dart.js:4703
oI @ new_embed.dart.js:1426
cb @ new_embed.dart.js:1522
bQ @ new_embed.dart.js:5056
Y @ new_embed.dart.js:4932
a4 @ new_embed.dart.js:4922
cp @ new_embed.dart.js:4923
$1 @ new_embed.dart.js:7540
$1 @ new_embed.dart.js:7805
ta @ new_embed.dart.js:513
(anonymous) @ new_embed.dart.js:522
load (async)
fj @ new_embed.dart.js:7474
pq @ new_embed.dart.js:1201
dO @ new_embed.dart.js:7795
bI @ new_embed.dart.js:3062
q6 @ new_embed.dart.js:3050
q5 @ new_embed.dart.js:3041
hM @ new_embed.dart.js:9846
(anonymous) @ new_embed.dart.js:9141
(anonymous) @ new_embed.dart.js:1311
$2 @ new_embed.dart.js:4753
dF @ new_embed.dart.js:1293
b6 @ new_embed.dart.js:9172
fP @ new_embed.dart.js:9106
$1 @ new_embed.dart.js:9318
cI @ new_embed.dart.js:5800
$0 @ new_embed.dart.js:5136
cL @ new_embed.dart.js:1388
ay @ new_embed.dart.js:5023
P @ new_embed.dart.js:4938
P @ new_embed.dart.js:4732
dE @ new_embed.dart.js:1297
(anonymous) @ new_embed.dart.js:9085
(anonymous) @ new_embed.dart.js:1311
$2 @ new_embed.dart.js:4753
$1 @ new_embed.dart.js:4745
cI @ new_embed.dart.js:5800
$0 @ new_embed.dart.js:5136
cL @ new_embed.dart.js:1388
ay @ new_embed.dart.js:5023
$1 @ new_embed.dart.js:4910
cJ @ new_embed.dart.js:5779
$1 @ new_embed.dart.js:5816
cI @ new_embed.dart.js:5800
$0 @ new_embed.dart.js:5136
cL @ new_embed.dart.js:1388
di @ new_embed.dart.js:5029
$0 @ new_embed.dart.js:5097
rz @ new_embed.dart.js:1418
rE @ new_embed.dart.js:1420
$1 @ new_embed.dart.js:4696
ta @ new_embed.dart.js:513
(anonymous) @ new_embed.dart.js:522
childList (async)
$1 @ new_embed.dart.js:4703
oI @ new_embed.dart.js:1426
cb @ new_embed.dart.js:1522
a6 @ new_embed.dart.js:5043
eb @ new_embed.dart.js:9533
dM @ new_embed.dart.js:8801
(anonymous) @ VM2873:3
$0 @ new_embed.dart.js:4896
$1 @ new_embed.dart.js:4904
cJ @ new_embed.dart.js:5779
$1 @ new_embed.dart.js:5816
q0 @ new_embed.dart.js:1327
q1 @ new_embed.dart.js:1317
eK @ new_embed.dart.js:8799
(anonymous) @ new_embed.dart.js:9084
(anonymous) @ new_embed.dart.js:1311
$2 @ new_embed.dart.js:4753
dF @ new_embed.dart.js:1293
bq @ new_embed.dart.js:9086
fb @ new_embed.dart.js:9073
qk @ new_embed.dart.js:3578
oX @ new_embed.dart.js:3648
(anonymous) @ new_embed.dart.js:10617
(anonymous) @ new_embed.dart.js:10612
dartProgram @ new_embed.dart.js:10615
(anonymous) @ new_embed.dart.js:10617
```
