### ISSUE TITLE
flutter did not work in my self hosted services

### ISSUE THREAD

**Issue by liudonghua123** [dart-lang/dart-pad#1495]
I tried to build a [docker](https://github.com/liudonghua123/dart-pad-docker/blob/master/Dockerfile-dart-pad) container to run the dart-pad, and the dart code run without problems. But when I run flutter code, I got the following errors in console logs.

The Dockerfile of dart-service is:

```docker
FROM google/dart

# install redis
RUN apt-get update -y
RUN apt-get install -y redis-server

# install the dependence
COPY dart-services/pubspec.yaml /dart-services/pubspec.yaml
WORKDIR /dart-services
RUN pub get

# install grinder globally
RUN pub global activate grinder
```

The Dockerfile of dart-pad is:

```docker
FROM google/dart

# install nodejs
RUN apt-get update -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

# install vulcanize
RUN npm i -g vulcanize

# install the dependence
COPY dart-pad /dart-pad
WORKDIR /dart-pad
RUN pub get

# install grinder globally
RUN pub global activate grinder
```

The docker-compose.yml is:

```docker
version: "3.7"
services:
  dart-pad:
    build:
      context: .
      dockerfile: Dockerfile-dart-pad
    networks:
      - nginx-proxy
    ports:
      - "8000"
    entrypoint: bash -c "cd /dart-pad && DARTPAD_BACKEND=http://dart-services.api.ynu.edu.cn grind serve-custom-backend"

  dart-services:
    build:
      context: .
      dockerfile: Dockerfile-dart-services
    networks:
      - nginx-proxy
    ports:
      - "8082"
    volumes:
      - ./dart-services:/dart-services
    entrypoint: bash -c "cd /dart-services && pub get && dart bin/server_dev.dart --port 8082"

networks:
  nginx-proxy:
    external:
      name: nginx-proxy-default
```

<details>
<summary>console logs</summary>

```
dart-services_1  | [INFO] rpc: Invoking API: /dartservices/v1 with HTTP method: POST on url: http://dart-services.api.ynu.edu.cn/api/dartservices/v1/compileDDC?alt=json.
dart-services_1  | [FINER] rpc: 
dart-services_1  | Request for API /dartservices/v1:
dart-services_1  |   Method: POST
dart-services_1  |   Path: /api/dartservices/v1/compileDDC
dart-services_1  |     accept: */*
dart-services_1  |     accept-encoding: gzip, deflate
dart-services_1  |     accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
dart-services_1  |     connection: close
dart-services_1  |     content-length: 690
dart-services_1  |     content-type: application/json; charset=utf-8
dart-services_1  |     host: dart-services.api.ynu.edu.cn
dart-services_1  |     origin: http://dart-pad.api.ynu.edu.cn
dart-services_1  |     referer: http://dart-pad.api.ynu.edu.cn/
dart-services_1  |     user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
dart-services_1  |     x-forwarded-for: 113.55.15.1
dart-services_1  |     x-forwarded-port: 80
dart-services_1  |     x-forwarded-proto: http
dart-services_1  |     x-forwarded-ssl: off
dart-services_1  |     x-real-ip: 113.55.15.1
dart-services_1  |   Body:
dart-services_1  |     {source: import 'package:flutter/material.dart';
dart-services_1  | 
dart-services_1  | final Color darkBlue = Color.fromARGB(255, 18, 32, 47);
dart-services_1  | 
dart-services_1  | void main() {
dart-services_1  |   runApp(MyApp());
dart-services_1  | }
dart-services_1  | 
dart-services_1  | class MyApp extends StatelessWidget {
dart-services_1  |   @override
dart-services_1  |   Widget build(BuildContext context) {
dart-services_1  |     return MaterialApp(
dart-services_1  |       theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
dart-services_1  |       debugShowCheckedModeBanner: false,
dart-services_1  |       home: Scaffold(
dart-services_1  |         body: Center(
dart-services_1  |           child: MyWidget(),
dart-services_1  |         ),
dart-services_1  |       ),
dart-services_1  |     );
dart-services_1  |   }
dart-services_1  | }
dart-services_1  | 
dart-services_1  | class MyWidget extends StatelessWidget {
dart-services_1  |   @override
dart-services_1  |   Widget build(BuildContext context) {
dart-services_1  |     return Text('Hello, World!', style: Theme.of(context).textTheme.headline4);
dart-services_1  |   }
dart-services_1  | }
dart-services_1  | }
dart-services_1  | 
dart-services_1  | [FINE] rpc: 
dart-services_1  | Invoking method: compileDDC with:
dart-services_1  |   Positional Parameters:
dart-services_1  |     Instance of 'CompileRequest'
dart-services_1  |   Named Parameters:
dart-services_1  | 
dart-services_1  | [INFO] common_server: CACHE: MISS for compileDDC
dart-services_1  | [INFO] compiler: Temp directory created: /tmp/dartpadXDWETB
dart-services_1  | [INFO] compiler: About to exec "/dart-services/flutter/bin/cache/dart-sdk/bin/dartdevc --modules=amd -s artifacts/flutter_web.dill -s /dart-services/flutter/bin/cache/flutter_web_sdk/flutter_web_sdk/kernel/flutter_ddc_sdk.dill -o /tmp/dartpadXDWETB/main.dart.js --module-name dartpad_main /tmp/dartpadXDWETB/bootstrap.dart --packages=/tmp/dartpadRSHTYB/.packages"
dart-services_1  | [INFO] compiler: Compiling: import 'package:flutter/material.dart';
dart-services_1  | 
dart-services_1  | final Color darkBlue = Color.fromARGB(255, 18, 32, 47);
dart-services_1  | 
dart-services_1  | void main() {
dart-services_1  |   runApp(MyApp());
dart-services_1  | }
dart-services_1  | 
dart-services_1  | class MyApp extends StatelessWidget {
dart-services_1  |   @override
dart-services_1  |   Widget build(BuildContext context) {
dart-services_1  |     return MaterialApp(
dart-services_1  |       theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
dart-services_1  |       debugShowCheckedModeBanner: false,
dart-services_1  |       home: Scaffold(
dart-services_1  |         body: Center(
dart-services_1  |           child: MyWidget(),
dart-services_1  |         ),
dart-services_1  |       ),
dart-services_1  |     );
dart-services_1  |   }
dart-services_1  | }
dart-services_1  | 
dart-services_1  | class MyWidget extends StatelessWidget {
dart-services_1  |   @override
dart-services_1  |   Widget build(BuildContext context) {
dart-services_1  |     return Text('Hello, World!', style: Theme.of(context).textTheme.headline4);
dart-services_1  |   }
dart-services_1  | }
dart-services_1  | 
dart-services_1  | [INFO] compiler: temp folder removed: /tmp/dartpadXDWETB
dart-services_1  | [WARNING] rpc: 
dart-services_1  | Response
dart-services_1  |   Status Code: 400
dart-services_1  |   Headers:
dart-services_1  |     access-control-allow-credentials: true
dart-services_1  |     access-control-allow-origin: *
dart-services_1  |     cache-control: no-cache, no-store, must-revalidate
dart-services_1  |     content-type: application/json; charset=utf-8
dart-services_1  |     expires: 0
dart-services_1  |     pragma: no-cache
dart-services_1  |   Exception:
dart-services_1  |     RPC Error with status: 400 and message: Error: Error when reading 'artifacts/flutter_web.dill': No such file or directory
dart-services_1  | Error: Error when reading 'flutter/bin/cache/flutter_web_sdk/flutter_web_sdk/kernel/flutter_ddc_sdk.dill': No such file or directory
dart-services_1  | We're sorry, you've found a bug in our compiler.
dart-services_1  | You can report this bug at:
dart-services_1  |     https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
dart-services_1  | Please include the information below in your report, along with
dart-services_1  | any other information that may help us track it down. Thanks!
dart-services_1  | -------------------- %< --------------------
dart-services_1  |     dartdevc -k arguments: --modules=amd -s artifacts/flutter_web.dill -s /dart-services/flutter/bin/cache/flutter_web_sdk/flutter_web_sdk/kernel/flutter_ddc_sdk.dill -o /tmp/dartpadXDWETB/main.dart.js --module-name dartpad_main /tmp/dartpadXDWETB/bootstrap.dart --packages=/tmp/dartpadRSHTYB/.packages
dart-services_1  |     dart --version: 2.8.0-dev.8.0.flutter-514a8d4c84 (Fri Feb 7 13:36:03 2020 +0000) on "linux_x64"
dart-services_1  | 
dart-services_1  | Crash when compiling file:///tmp/dartpadXDWETB/bootstrap.dart,
dart-services_1  | at character offset null:
dart-services_1  | Bad state: Empty input given.
dart-services_1  | #0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
dart-services_1  | #1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
dart-services_1  | #2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
dart-services_1  | #3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
dart-services_1  | #4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
dart-services_1  | #5      ProcessedOptions.loadInputSummaries.<anonymous closure> (package:front_end/src/base/processed_options.dart:376:35)
dart-services_1  | #6      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
dart-services_1  | #7      ListIterable.toList (dart:_internal/iterable.dart:221:19)
dart-services_1  | #8      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:376:67)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:89:50)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
dart-services_1  | #11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
dart-services_1  | #12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
dart-services_1  | #13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
dart-services_1  | #15     new Future.sync (dart:async/future.dart:224:31)
dart-services_1  | #16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
dart-services_1  | #17     _rootRun (dart:async/zone.dart:1126:13)
dart-services_1  | #18     _CustomZone.run (dart:async/zone.dart:1023:19)
dart-services_1  | #19     _runZoned (dart:async/zone.dart:1518:10)
dart-services_1  | #20     runZoned (dart:async/zone.dart:1465:12)
dart-services_1  | #21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
dart-services_1  | #22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
dart-services_1  | #23     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
dart-services_1  | #24     compile (package:front_end/src/api_unstable/ddc.dart:194:13)
dart-services_1  | #25     _compile (package:dev_compiler/src/kernel/command.dart:329:20)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #26     compile (package:dev_compiler/src/kernel/command.dart:45:18)
dart-services_1  | #27     compile (package:dev_compiler/src/compiler/shared_command.dart:391:10)
dart-services_1  | #28     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
dart-services_1  | #29     _rootRun (dart:async/zone.dart:1126:13)
dart-services_1  | #30     _CustomZone.run (dart:async/zone.dart:1023:19)
dart-services_1  | #31     _runZoned (dart:async/zone.dart:1518:10)
dart-services_1  | #32     runZoned (dart:async/zone.dart:1465:12)
dart-services_1  | #33     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
dart-services_1  | #34     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
dart-services_1  | #35     _rootRun (dart:async/zone.dart:1126:13)
dart-services_1  | #36     _CustomZone.run (dart:async/zone.dart:1023:19)
dart-services_1  | #37     _runZoned (dart:async/zone.dart:1518:10)
dart-services_1  | #38     runZoned (dart:async/zone.dart:1465:12)
dart-services_1  | #39     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #40     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
dart-services_1  | #41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
dart-services_1  | #42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
dart-services_1  | 
dart-services_1  | 
dart-services_1  | #0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
dart-services_1  | #1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
dart-services_1  | #2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
dart-services_1  | #3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
dart-services_1  | #4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
dart-services_1  | #5      ProcessedOptions.loadInputSummaries.<anonymous closure> (package:front_end/src/base/processed_options.dart:376:35)
dart-services_1  | #6      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
dart-services_1  | #7      ListIterable.toList (dart:_internal/iterable.dart:221:19)
dart-services_1  | #8      ProcessedOptions.loadInputSummaries (package:front_end/src/base/processed_options.dart:376:67)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:89:50)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
dart-services_1  | #11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
dart-services_1  | #12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
dart-services_1  | #13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
dart-services_1  | #15     new Future.sync (dart:async/future.dart:224:31)
dart-services_1  | #16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
dart-services_1  | #17     _rootRun (dart:async/zone.dart:1126:13)
dart-services_1  | #18     _CustomZone.run (dart:async/zone.dart:1023:19)
dart-services_1  | #19     _runZoned (dart:async/zone.dart:1518:10)
dart-services_1  | #20     runZoned (dart:async/zone.dart:1465:12)
dart-services_1  | #21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
dart-services_1  | #22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
dart-services_1  | #23     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
dart-services_1  | #24     compile (package:front_end/src/api_unstable/ddc.dart:194:13)
dart-services_1  | #25     _compile (package:dev_compiler/src/kernel/command.dart:329:20)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #26     compile (package:dev_compiler/src/kernel/command.dart:45:18)
dart-services_1  | #27     compile (package:dev_compiler/src/compiler/shared_command.dart:391:10)
dart-services_1  | #28     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
dart-services_1  | #29     _rootRun (dart:async/zone.dart:1126:13)
dart-services_1  | #30     _CustomZone.run (dart:async/zone.dart:1023:19)
dart-services_1  | #31     _runZoned (dart:async/zone.dart:1518:10)
dart-services_1  | #32     runZoned (dart:async/zone.dart:1465:12)
dart-services_1  | #33     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
dart-services_1  | #34     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
dart-services_1  | #35     _rootRun (dart:async/zone.dart:1126:13)
dart-services_1  | #36     _CustomZone.run (dart:async/zone.dart:1023:19)
dart-services_1  | #37     _runZoned (dart:async/zone.dart:1518:10)
dart-services_1  | #38     runZoned (dart:async/zone.dart:1465:12)
dart-services_1  | #39     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #40     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
dart-services_1  | #41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
dart-services_1  | #42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
dart-services_1  | 
dart-services_1  | 
dart-services_1  | 
dart-services_1  | 
dart-services_1  | #0      _convertBadRequest (package:dart_services/src/common_server.dart:130:7)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #1      CommonServer.compileDDC (package:dart_services/src/common_server.dart:68:7)
dart-services_1  | #2      _InstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:327:37)
dart-services_1  | #3      _InstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:323:25)
dart-services_1  | #4      ApiConfigMethod.invokeWithBody (package:rpc/src/config/method.dart:320:22)
dart-services_1  | <asynchronous suspension>
dart-services_1  | #5      ApiConfigMethod.invokeHttpRequest.<anonymous closure> (package:rpc/src/config/method.dart:174:21)
dart-services_1  | #6      _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
dart-services_1  | #7      _rootRun (dart:async/zone.dart:1126:13)
dart-services_1  | #8      _CustomZone.run (dart:async/zone.dart:1023:19)
dart-services_1  | #9      _runZoned (dart:async/zone.dart:1518:10)
dart-services_1  | #10     runZoned (dart:async/zone.dart:1465:12)
dart-services_1  | #11     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
dart-services_1  | #12     fork (package:gcloud/service_scope.dart:104:30)
dart-services_1  | #13     ApiConfigMethod.invokeHttpRequest (package:rpc/src/config/method.dart:164:12)
dart-services_1  | #14     ApiConfig.handleHttpRequest (package:rpc/src/config/api.dart:38:25)
dart-services_1  | #15     ApiServer.handleHttpApiRequest (package:rpc/src/server.dart:123:30)
dart-services_1  | #16     EndpointsServer._apiHandler (package:dart_services/services_dev.dart:144:10)
dart-services_1  | #17     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70:46)
dart-services_1  | #18     new Future.sync (dart:async/future.dart:224:31)
dart-services_1  | #19     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70:23)
dart-services_1  | #20     _rootRunUnary (dart:async/zone.dart:1134:38)
dart-services_1  | #21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
dart-services_1  | #22     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
dart-services_1  | #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
dart-services_1  | #24     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
dart-services_1  | #25     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:389:9)
dart-services_1  | #26     _rootRun (dart:async/zone.dart:1126:13)
dart-services_1  | #27     _CustomZone.run (dart:async/zone.dart:1023:19)
dart-services_1  | #28     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
dart-services_1  | #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
dart-services_1  | #30     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
dart-services_1  | #31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
dart-services_1  | #32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
dart-services_1  | #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
dart-services_1  | 
dart-services_1  | 2020-03-06T06:15:30.186468  0:00:00.064974 POST    [400] /api/dartservices/v1/compileDDC?alt=json

```
</details>

**Comment by RedBrogdon** [comment]
Have you taken a look at the dockerfile and grinder file contained in the dart-services project?

https://github.com/dart-lang/dart-services/blob/master/Dockerfile
https://github.com/dart-lang/dart-services/blob/master/tool/grind.dart

Part of getting an instance up and running is getting the Fltuter SDK submodule initialized. If you take a look at the `setupFlutterSubmodule` and `buildStorageArtifacts`, for example, you can see where some of that gets done (including creation of the dill file that's referenced in the error log you posted).

**Comment by liudonghua123** [comment]
@RedBrogdon Thanks, now I understand it. 😃
