### ISSUE TITLE
Running flask server under web/ gives 404 not found for route '/'

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart-pad#1596]
```
cd web
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt
python main.py
```
running flask server as above.

```
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-995-479
127.0.0.1 - - [18/Jul/2020 16:35:44] "GET / HTTP/1.1" 404 -
```

gives above 404. how do i locally run dartpad?

**Comment by softmarshmallow** [comment]
I managed to fix above issue by placing
```

if __name__ == '__main__':
    # This is used when running locally only.
    app.run(host='127.0.0.1', port=8080, debug=True)
```
at the end of the line, referencing https://stackoverflow.com/a/32805740/5463235 .

but i still get style.css not found errors, and the page seems like not able to run.

can you provide more informations & setup guidelines in order to run it in local env? 

(also i tried uploading to google app engine, it shows the same errrs, scss and others wont compile.)

thanks!

**Comment by RedBrogdon** [comment]
Hi, @softmarshmallow! DartPad is typically run using [`grinder`](https://pub.dev/packaged/grinder), a Dart package for automating simple command line tasks like spinning up a server. You can use it by following the instructions on pub.dev for installing grinder, and then typing `grind serve` from the command line.

See this file for the particular tasks available for dart-pad and what they do:

https://github.com/dart-lang/dart-pad/blob/master/tool/grind.dart

**Comment by softmarshmallow** [comment]
Hi, @RedBrogdon thanks for the reply. i followed the instruction as mentioned, now i get this
```
grinder running build

build
  /usr/local/Cellar/dart/2.8.4/libexec/bin/pub run build_runner build -r -o web:build
  [INFO] Generating build script...
  [INFO] Generating build script completed, took 349ms
  
  [INFO] Initializing inputs
  [INFO] Reading cached asset graph...
  [INFO] Reading cached asset graph completed, took 217ms
  
  [INFO] Checking for updates since last build...
  [INFO] Checking for updates since last build completed, took 794ms
  
  [INFO] Running build...
  [INFO] Running build completed, took 251ms
  
  [INFO] Caching finalized dependency graph...
  [INFO] Caching finalized dependency graph completed, took 146ms
  
  [INFO] Reading manifest at build/.build.manifest...
  [INFO] Reading manifest at build/.build.manifest completed, took 1ms
  
  [INFO] Deleting previous outputs in `build`...
  [INFO] Deleting previous outputs in `build` completed, took 149ms
  
  [INFO] Creating merged output dir `build`...
  [INFO] Creating merged output dir `build` completed, took 1.1s
  
  [INFO] Writing asset manifest...
  [INFO] Writing asset manifest completed, took 9ms
  
  [INFO] Succeeded after 1.6s with 0 outputs (0 actions)
  build/scripts/playground.dart.js compiled to 534k
  build/scripts/embed_dart.dart.js compiled to 521k
  build/scripts/embed_flutter.dart.js compiled to 521k
  build/scripts/embed_html.dart.js compiled to 521k
  build/scripts/embed_inline.dart.js compiled to 521k
  Removed 0 Dart files
  build/index.html original: 16k

ProcessException: No such file or directory
  Command: vulcanize --strip-comments --inline-css --inline-scripts --exclude  scripts/embed_dart.dart.js --exclude  scripts/embed_flutter.dart.js --exclude  scripts/embed_html.dart.js --exclude  scripts/embed_inline.dart.js --exclude scripts/playground.dart.js --exclude scripts/codemirror.js index.html
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:640:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      vulcanize (file:///Users/Genoplan/Downloads/dart-pad-master/tool/grind.dart:207:24)
#4      build (file:///Users/Genoplan/Downloads/dart-pad-master/tool/grind.dart:169:3)
#5      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:1093:36)
#6      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:244:25)
#7      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:79:38)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     ZonedValue.withValue (package:grinder/src/utils.dart:112:12)
#13     GrinderTask.execute (package:grinder/src/grinder_task.dart:63:27)
#14     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#15     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#16     Future.forEach.<anon> (dart:async/future.dart:494:26)
#17     Future.doWhile.<anon> (dart:async/future.dart:536:26)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#19     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1413:26)
#20     Future.doWhile (dart:async/future.dart:551:18)
#21     Future.forEach (dart:async/future.dart:492:12)
#22     Grinder.start (package:grinder/src/grinder.dart:167:21)
#23     runTasks (package:grinder/src/cli.dart:67:39)
#24     grind (package:grinder/grinder.dart:46:12)
```


I'll need more kind instruction in order to deploy on the local machine

(should i open a new issue for this?)

**Comment by softmarshmallow** [comment]
running `npm install -g vulcanize`

before `grind serve`

worked.



(found this under travis.sh) -- do i need to execute this?


conclusion, resolved in a weird way.

+ need documentation for `tool/travis.sh`

**Comment by softmarshmallow** [comment]
@RedBrogdon  I need reply for the last comment
