### ISSUE TITLE
Document vulcanize dependency

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart-pad#1657]
When i run grid serve, after proper dependency resolvement. I get this.
```
ProcessException: No such file or directory
  Command: vulcanize --strip-comments --inline-css --inline-scripts --exclude  scripts/embed_dart.dart.js --exclude  scripts/embed_flutter.dart.js --exclude  scripts/embed_html.dart.js --exclude  scripts/embed_inline.dart.js --exclude scripts/playground.dart.js --exclude scripts/codemirror.js index.html
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:640:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      vulcanize (file:///Users/aa/Documents/GitHub/dart-pad/tool/grind.dart:207:24)
#4      build (file:///Users/aa/Documents/GitHub/dart-pad/tool/grind.dart:169:3)
#5      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:1093:36)
#6      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:244:25)
#7      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:77:38)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     ZonedValue.withValue (package:grinder/src/utils.dart:113:12)
#13     GrinderTask.execute (package:grinder/src/grinder_task.dart:63:27)
#14     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#15     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#16     Future.forEach.<anon> (dart:async/future.dart:494:26)
#17     Future.doWhile.<anon> (dart:async/future.dart:536:26)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#19     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1413:26)
#20     Future.doWhile (dart:async/future.dart:551:18)
#21     Future.forEach (dart:async/future.dart:492:12)
#22     Grinder.start (package:grinder/src/grinder.dart:167:21)
#23     runTasks (package:grinder/src/cli.dart:67:38)
```

**Comment by RedBrogdon** [comment]
It's currently documented in the Contributor's Guide:

https://github.com/dart-lang/dart-pad/blob/1692c9ffe69c326b2ee376b6749a5a50e010f377/CONTRIBUTING.md#L43
