### ISSUE TITLE
Deploy task fails during integration tests

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2324]
```
  00:00 +34: test/e2e/playground_test.dart: (setUpAll)
  [INFO] Generating build script...
  [INFO] Generating build script completed, took 204ms
  
  [INFO] Initializing inputs
  [INFO] Reading cached asset graph...
  [INFO] Reading cached asset graph completed, took 218ms
  
  [INFO] Checking for updates since last build...
  [INFO] Checking for updates since last build completed, took 518ms
  
  [INFO] Running build...
  [INFO] 1.7s elapsed, 1/5 actions completed.
  [INFO] 2.7s elapsed, 93/100 actions completed.
  [INFO] 3.9s elapsed, 93/100 actions completed.
  [INFO] 5.0s elapsed, 93/100 actions completed.
  [INFO] 6.1s elapsed, 93/100 actions completed.
  [INFO] 12.5s elapsed, 93/100 actions completed.
  [INFO] Running build completed, took 12.7s
  
  [INFO] Caching finalized dependency graph...
  [INFO] Caching finalized dependency graph completed, took 222ms
  
  [SEVERE] json_serializable:json_serializable on test/sharing/gist_loader_test.dart (cached):
  
  InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
  
  [SEVERE] Failed after 12.9s
  00:16 +34 -1: test/e2e/playground_test.dart: (setUpAll) [E]
    failed with exit code 1
    package:grinder/src/run.dart 43:5        run
    package:grinder/grinder_sdk.dart 239:19  Pub.run
    package:grinder/grinder_sdk.dart 599:16  _PubLocalApp.run
    test/e2e/playground_test.dart 20:34      main.build
    test/e2e/playground_test.dart 45:5       main.<fn>
    test/e2e/playground_test.dart 44:12      main.<fn>
  
  00:16 +34 -1: test/e2e/playground_test.dart: (tearDownAll)
  00:16 +34 -2: test/e2e/playground_test.dart: (tearDownAll) [E]
    LateInitializationError: Local 'frontEndServer' has not been initialized.
    dart:_internal                      LateError._throwLocalNotInitialized
    test/e2e/playground_test.dart 62:5  main.<fn>
  
  00:16 +34 -2: Some tests failed.
  
  Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
  For example, 'dart test --chain-stack-traces'.

failed with exit code 1
#0      runAsync (package:grinder/src/run.dart:108:5)
<asynchronous suspension>
#1      testCli (file:///Users/ryjohn/code/github/dart-lang/dart-pad/tool/grind.dart:24:20)
<asynchronous suspension>
#2      _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1657:12)
<asynchronous suspension>
```

**Comment by johnpryan** [comment]
Duplicate of https://github.com/dart-lang/dart-pad/issues/2360
