### ISSUE TITLE
Channel selector is not functional

### ISSUE THREAD

**Issue by yanok** [dart-lang/dart-pad#2491]
## What happened?

Channel selector stopped working recently. First, it shows as "Channel" on load (instead of "stable" previously) and second, if I click on it, nothing happens. So it really looks like channel selection options somehow disappeared.

## Steps to reproduce problem

1. Open https://dartpad.dev.
2. Observe channel selector shows as "Channel"
3. Click on it
4. Observe that nothing happens.

### Browser

Browser: Google Chrome

Version: 112.0.5615.121

> Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Yes, but it's reproducible with ad blocker disabled.

> Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

Yes, see below.

```
caught FormatException: Protobuf JSON decoding failed at: root["flutterEngineSha"]. Unknown field name 'flutterEngineSha'
flutterEngineSha
    at Object.a (https://dartpad.dev/scripts/playground.dart.js:453:3)
    at vZ.$2 (https://dartpad.dev/scripts/playground.dart.js:18820:9)
    at mo.S (https://dartpad.dev/scripts/playground.dart.js:8738:12)
    at Object.bY (https://dartpad.dev/scripts/playground.dart.js:5889:24)
    at vW.$2 (https://dartpad.dev/scripts/playground.dart.js:18745:15)
    at Object.Gv (https://dartpad.dev/scripts/playground.dart.js:5267:60)
    at eM.jW (https://dartpad.dev/scripts/playground.dart.js:18554:10)
    at https://dartpad.dev/scripts/playground.dart.js:15319:3
    at w8.a (https://dartpad.dev/scripts/playground.dart.js:1639:63)
    at w8.$2 (https://dartpad.dev/scripts/playground.dart.js:7333:14)
a @ playground.dart.js:453
Dv @ playground.dart.js:2474
$0 @ playground.dart.js:8191
Gw @ playground.dart.js:1757
GD @ playground.dart.js:1759
$1 @ playground.dart.js:7287
Hr @ playground.dart.js:534
(anonymous) @ playground.dart.js:542
childList (async)
$1 @ playground.dart.js:7294
AB @ playground.dart.js:1764
dV @ playground.dart.js:1833
lV @ playground.dart.js:7668
bJ @ playground.dart.js:7664
af @ playground.dart.js:7572
$1 @ playground.dart.js:16366
hu @ playground.dart.js:8223
$0 @ playground.dart.js:7745
fR @ playground.dart.js:1721
d0 @ playground.dart.js:7648
FX @ playground.dart.js:1807
$1 @ playground.dart.js:7817
$1 @ playground.dart.js:10950
Hr @ playground.dart.js:534
(anonymous) @ playground.dart.js:542
load (async)
lT @ playground.dart.js:10126
jl @ playground.dart.js:10125
CI @ playground.dart.js:5877
fK @ playground.dart.js:10940
cG @ playground.dart.js:10929
gO @ playground.dart.js:7798
(anonymous) @ playground.dart.js:16329
(anonymous) @ playground.dart.js:1639
$2 @ playground.dart.js:7333
$1 @ playground.dart.js:7327
hu @ playground.dart.js:8223
$0 @ playground.dart.js:7745
fR @ playground.dart.js:1721
ck @ playground.dart.js:7654
$0 @ playground.dart.js:7710
Gw @ playground.dart.js:1757
GD @ playground.dart.js:1759
$1 @ playground.dart.js:7287
Hr @ playground.dart.js:534
(anonymous) @ playground.dart.js:542
childList (async)
$1 @ playground.dart.js:7294
AB @ playground.dart.js:1764
dV @ playground.dart.js:1833
lV @ playground.dart.js:7668
bJ @ playground.dart.js:7664
hE @ playground.dart.js:1656
ds @ playground.dart.js:13983
j4 @ playground.dart.js:12196
(anonymous) @ playground.dart.js:575
$0 @ playground.dart.js:7531
$1 @ playground.dart.js:7539
dD @ playground.dart.js:8203
$1 @ playground.dart.js:8236
DD @ playground.dart.js:1684
DE @ playground.dart.js:1680
kX @ playground.dart.js:12194
(anonymous) @ playground.dart.js:4216
(anonymous) @ playground.dart.js:1639
$2 @ playground.dart.js:7333
a9 @ playground.dart.js:1625
rP @ playground.dart.js:4218
(anonymous) @ playground.dart.js:4109
(anonymous) @ playground.dart.js:1639
$2 @ playground.dart.js:7333
a9 @ playground.dart.js:1625
t8 @ playground.dart.js:4198
(anonymous) @ playground.dart.js:5776
(anonymous) @ playground.dart.js:1639
$2 @ playground.dart.js:7333
a9 @ playground.dart.js:1625
wu @ playground.dart.js:5778
(anonymous) @ playground.dart.js:20564
(anonymous) @ playground.dart.js:20558
dartProgram @ playground.dart.js:20561
(anonymous) @ playground.dart.js:20564
```

### Machine

Operating system: GNU/Linux

Version:

**Comment by johnpryan** [comment]
This was due to dart-services and dart-pad getting out of sync, but should be fixed now https://github.com/dart-lang/dart-pad/pull/2490 has been deployed.
