### ISSUE TITLE
Show more stack trace information

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2668]
Exceptions in DartPad should contain more information like the line number and full stack trace.

## Example
This program throws a TypeError:

```
void main() {
  var map = <String, dynamic>{};
  String s = map['foo'];
  print(s);
}
```

```
Unhandled exception:
type 'Null' is not a subtype of type 'String'
#0      main (file:///Users/ryjohn/Desktop/foo/bin/foo.dart:3:10)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

But in DartPad, only the first line is printed:

```
Uncaught Error: TypeError: null: type 'JSNull' is not a subtype of type 'String'
```

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/dart-pad/issues/3008.
